### ISSUE TITLE
Incompatible Files

### ISSUE THREAD

**Issue by CreativeRobotics** [amberspyglass/parts#1]
I can't get any of the DWG or DXF files to open in Solidworks (2011) or in Illustrator. It tells me that they are of an incompatible/incomplete type

**Comment by cvoinescu** [comment]
Hi.

The DWGs are created with an up-to-date version of DraftSight, so they're the 
2013 format.  DXFs are created from the DWGs using Teigha File Converter, again 
outputting the 2013 format.  You can use that to convert either the DWG or the 
DXF files into an older version (R13, 2007 etc) that may open in SolidWorks 
2011.  If you identify a format that works, I can convert all the files into 
that format and upload them.

Best regards,

Catalin

**Comment by CreativeRobotics** [comment]
Thanks, I didn't know about Teigha, very handy - it would be good to include what you wrote above in the readme file for anyone else like me ... ;)
